// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package orders

import (
	"database/sql"
	"time"
)

type CounterOrder struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	OrderDate     time.Time `json:"order_date"`
	TotalAmount   string    `json:"total_amount"`
	PaymentMethod string    `json:"payment_method"`
	OrderStatus   string    `json:"order_status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type CounterOrderItem struct {
	ID             int32          `json:"id"`
	CounterOrderID int32          `json:"counter_order_id"`
	ProductID      int32          `json:"product_id"`
	ItemStatus     string         `json:"item_status"`
	Quantity       int32          `json:"quantity"`
	Notes          sql.NullString `json:"notes"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
