// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package orders

import (
	"context"
)

type Querier interface {
	AreAllOrderItemsReady(ctx context.Context, counterOrderID int32) (bool, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CounterOrder, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (CounterOrderItem, error)
	DeleteOrder(ctx context.Context, id int32) error
	DeleteOrderItem(ctx context.Context, id int32) error
	GetOrderDetailById(ctx context.Context, id int32) ([]GetOrderDetailByIdRow, error)
	GetOrderItemsByOrderId(ctx context.Context, counterOrderID int32) ([]GetOrderItemsByOrderIdRow, error)
	GetOrdersByUserId(ctx context.Context, userID int32) ([]CounterOrder, error)
	GetTotalAmountByOrderId(ctx context.Context, counterOrderID int32) (int64, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (CounterOrder, error)
	UpdateOrderItemStatus(ctx context.Context, arg UpdateOrderItemStatusParams) (CounterOrderItem, error)
}

var _ Querier = (*Queries)(nil)
