// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package product

import (
	"time"

	"github.com/shopspring/decimal"
)

type Product struct {
	ID                 int32           `json:"id"`
	Name               string          `json:"name"`
	Description        string          `json:"description"`
	Price              decimal.Decimal `json:"price"`
	Category           string          `json:"category"`
	IsAvailable        bool            `json:"is_available"`
	EstPreparationTime int32           `json:"est_preparation_time"`
	ItemType           string          `json:"item_type"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}
