// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package product

import (
	"context"
)

type Querier interface {
	AddProduct(ctx context.Context, arg AddProductParams) (Product, error)
	DeleteProduct(ctx context.Context, id int32) (Product, error)
	GetProductById(ctx context.Context, id int32) (Product, error)
	SearchProductsByCategory(ctx context.Context, arg SearchProductsByCategoryParams) ([]Product, error)
	SearchProductsByName(ctx context.Context, arg SearchProductsByNameParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
