CREATE TABLE "counter_orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "order_date" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "total_amount" DECIMAL NOT NULL,
  "payment_method" VARCHAR(255) NOT NULL,
  "order_status" VARCHAR(255) NOT NULL DEFAULT 'pending',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT '0001-01-01 00:00:00Z',
  CONSTRAINT "fk_counter_orders_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX "idx_counter_orders_user_id" ON "counter_orders" ("user_id");
CREATE INDEX "idx_order_date" ON "counter_orders" ("order_date");

CREATE TABLE "counter_order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "counter_order_id" INT NOT NULL,
  "product_id" INT NOT NULL,
  "item_status" VARCHAR(255) NOT NULL DEFAULT 'pending',
  "quantity" INT NOT NULL,
  "notes" TEXT DEFAULT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT '0001-01-01 00:00:00Z',
  CONSTRAINT "fk_counter_order_items_order" FOREIGN KEY ("counter_order_id") REFERENCES "counter_orders" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_counter_order_items_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE
);

CREATE INDEX "idx_counter_order_items_order_id" ON "counter_order_items" ("counter_order_id");
CREATE INDEX "idx_counter_order_items_product_id" ON "counter_order_items" ("product_id");
