CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "description" TEXT,
  "price" DECIMAL,
  "category" VARCHAR(100),
  "is_available" BOOLEAN,
  "item_type" VARCHAR(255) DEFAULT 'barista', 
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP
);

CREATE INDEX "idx_product_name" ON "products" ("name");

CREATE INDEX "idx_product_category" ON "products" ("category");