CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL,
  "price" DECIMAL NOT NULL,
  "category" VARCHAR(100) NOT NULL,
  "is_available" BOOLEAN NOT NULL DEFAULT TRUE,
  "item_type" VARCHAR(255) NOT NULL DEFAULT 'barista', 
  "created_at" timestamptz NOT NULL DEFAULT (now()) ,
  "updated_at"  timestamptz NOT NULL DEFAULT '0001-01-01 00:00:00Z'
);

CREATE INDEX "idx_product_name" ON "products" ("name");

CREATE INDEX "idx_product_category" ON "products" ("category");