CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "email" VARCHAR(255) UNIQUE,
  "password" VARCHAR(255),
  "phone_number" VARCHAR(20) UNIQUE,
  "is_verified" BOOLEAN DEFAULT false,
  "role" VARCHAR(255) DEFAULT 'customer',
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP
);

CREATE UNIQUE INDEX "idx_phone_number" ON "users" ("phone_number");

CREATE UNIQUE INDEX "idx_email" ON "users" ("email");