CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "phone_number" VARCHAR(20) UNIQUE NOT NULL,
  "is_verified" BOOLEAN DEFAULT false,
  "role" VARCHAR(255) DEFAULT 'customer',
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "password_changed_at" timestamptz NOT NULL DEFAULT '0001-01-01 00:00:00Z'
);

CREATE UNIQUE INDEX "idx_phone_number" ON "users" ("phone_number");

CREATE UNIQUE INDEX "idx_email" ON "users" ("email");