// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package user

import (
	"database/sql"
	"time"
)

type User struct {
	ID                int32          `json:"id"`
	Name              string         `json:"name"`
	Email             string         `json:"email"`
	Password          string         `json:"password"`
	PhoneNumber       string         `json:"phone_number"`
	IsVerified        sql.NullBool   `json:"is_verified"`
	Role              sql.NullString `json:"role"`
	CreatedAt         time.Time      `json:"created_at"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
}
