// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package user

import (
	"database/sql"
)

type User struct {
	ID          int32          `json:"id"`
	Name        sql.NullString `json:"name"`
	Email       sql.NullString `json:"email"`
	Password    sql.NullString `json:"password"`
	PhoneNumber sql.NullString `json:"phone_number"`
	IsVerified  sql.NullBool   `json:"is_verified"`
	Role        sql.NullString `json:"role"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
