// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package user

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByPhoneNumber(ctx context.Context, phoneNumber sql.NullString) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
